name: test-and-build

run-name: Tests and prepares build for deploying

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-task@v2

      - name: Prepare env
        run: task -d .ci env

      - name: Initialize everything
        run: task -d .ci init

      - name: 'Cache node_modules: check'
        uses: actions/cache/restore@v3
        id: cache-node-modules
        with:
          path: |
            frontend/node_modules
            signaller/node_modules
          key: node-modules-${{ hashFiles('frontend/yarn.lock', 'backend/yarn.lock') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        name: 'Cache node_modules doesn''t exist: install'
        run: task -d .ci yarn

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        name: 'Cache node_modules doesn''t exist: save node_modules to cache'
        uses: actions/cache/save@v3
        with:
          path: |
            frontend/node_modules
            backend/node_modules
          key: node-modules-${{ hashFiles('frontend/yarn.lock', 'backend/yarn.lock') }}

      - name: Set permissions for node_modules
        run: sudo chmod -R 777 frontend/node_modules

      - name: Build frontend for testing
        run: task -d .ci frontend:build

      - name: Create vars for wrangler
        run: echo -e "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}\nTWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" > backend/.dev.vars

      - name: Start project
        run: task -d .ci up

      - name: Start e2e testing
        run: task -d .ci test

      - name: Rebuild frontend for production
        run: task -d .ci frontend:build -- \'VITE_WEBSOCKET_URL=${{ vars.VITE_WEBSOCKET_URL }}\'

      - name: 'Uploads ''frontend/dist'' artifact'
        uses: actions/upload-artifact@v3
        with:
          path: frontend/dist
          name: frontend-dist
